///////////////////////////////////////////////////////////////////////////////
//
// THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT MODIFY IT BY HAND.
//
///////////////////////////////////////////////////////////////////////////////
#pragma once
// 
// Namespace http://schemas.microsoft.com/windows/2012/10/wdp/printV12
// 
#define NAMESPACE_ENCODING_PRINT_V12 WSDXML_NAMESPACE_ENCODING(0,1)
extern WSDXML_NAME Names_PrintV12[];
extern WSDXML_NAMESPACE Namespace_PrintV12;


#define PRINTV12_SetPrinterElementsRequestType     WSDXML_NAME_ENCODING(0,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_SetPrinterElementsResponseType    WSDXML_NAME_ENCODING(1,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_PrinterElementsToSetType          WSDXML_NAME_ENCODING(2,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_ElementToSetType                  WSDXML_NAME_ENCODING(3,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_ElementPathExtType                WSDXML_NAME_ENCODING(4,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_PrinterElementsToSetResultsType   WSDXML_NAME_ENCODING(5,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_ElementToSetResultType            WSDXML_NAME_ENCODING(6,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_ElementSetResultValuesType        WSDXML_NAME_ENCODING(7,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_SupportsWSPrintV12                WSDXML_NAME_ENCODING(8,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_SetPrinterElementsRequest         WSDXML_NAME_ENCODING(9,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_SetPrinterElementsResponse        WSDXML_NAME_ENCODING(10,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_PrinterServiceV12Type             WSDXML_NAME_ENCODING(11,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_SetPrinterElementsRequestMsg      WSDXML_NAME_ENCODING(12,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_SetPrinterElementsResponseMsg     WSDXML_NAME_ENCODING(13,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_SetPrinterElements                WSDXML_NAME_ENCODING(14,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_ElementsToSet                     WSDXML_NAME_ENCODING(15,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_ElementToSet                      WSDXML_NAME_ENCODING(16,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_ElementPath                       WSDXML_NAME_ENCODING(17,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_Any                               WSDXML_NAME_ENCODING(18,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_Element                           WSDXML_NAME_ENCODING(19,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_Body                              WSDXML_NAME_ENCODING(20,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_ElementsToSetResults              WSDXML_NAME_ENCODING(21,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_ElementToSetResult                WSDXML_NAME_ENCODING(22,NAMESPACE_ENCODING_PRINT_V12)
#define PRINTV12_Result                            WSDXML_NAME_ENCODING(23,NAMESPACE_ENCODING_PRINT_V12)

extern WSDXML_NAMESPACE* PrinterServiceV12TypeNamespaces[1];
#define PrinterServiceV12TypeRegisterNamespaces(pContext) pContext->SetNamespaces(PrinterServiceV12TypeNamespaces,(sizeof(PrinterServiceV12TypeNamespaces) / sizeof(PrinterServiceV12TypeNamespaces[0])),1)


#define NAME_PRINTV12_SetPrinterElementsRequestType     (&(Names_PrintV12[0]))
#define NAME_PRINTV12_SetPrinterElementsResponseType    (&(Names_PrintV12[1]))
#define NAME_PRINTV12_PrinterElementsToSetType          (&(Names_PrintV12[2]))
#define NAME_PRINTV12_ElementToSetType                  (&(Names_PrintV12[3]))
#define NAME_PRINTV12_ElementPathExtType                (&(Names_PrintV12[4]))
#define NAME_PRINTV12_PrinterElementsToSetResultsType   (&(Names_PrintV12[5]))
#define NAME_PRINTV12_ElementToSetResultType            (&(Names_PrintV12[6]))
#define NAME_PRINTV12_ElementSetResultValuesType        (&(Names_PrintV12[7]))
#define NAME_PRINTV12_SupportsWSPrintV12                (&(Names_PrintV12[8]))
#define NAME_PRINTV12_SetPrinterElementsRequest         (&(Names_PrintV12[9]))
#define NAME_PRINTV12_SetPrinterElementsResponse        (&(Names_PrintV12[10]))
#define NAME_PRINTV12_PrinterServiceV12Type             (&(Names_PrintV12[11]))
#define NAME_PRINTV12_SetPrinterElementsRequestMsg      (&(Names_PrintV12[12]))
#define NAME_PRINTV12_SetPrinterElementsResponseMsg     (&(Names_PrintV12[13]))
#define NAME_PRINTV12_SetPrinterElements                (&(Names_PrintV12[14]))
#define NAME_PRINTV12_ElementsToSet                     (&(Names_PrintV12[15]))
#define NAME_PRINTV12_ElementToSet                      (&(Names_PrintV12[16]))
#define NAME_PRINTV12_ElementPath                       (&(Names_PrintV12[17]))
#define NAME_PRINTV12_Any                               (&(Names_PrintV12[18]))
#define NAME_PRINTV12_Element                           (&(Names_PrintV12[19]))
#define NAME_PRINTV12_Body                              (&(Names_PrintV12[20]))
#define NAME_PRINTV12_ElementsToSetResults              (&(Names_PrintV12[21]))
#define NAME_PRINTV12_ElementToSetResult                (&(Names_PrintV12[22]))
#define NAME_PRINTV12_Result                            (&(Names_PrintV12[23]))

typedef struct _ELEMENT_TO_SET_TYPE ELEMENT_TO_SET_TYPE;
typedef struct _ELEMENT_TO_SET_TYPE_LIST ELEMENT_TO_SET_TYPE_LIST;
typedef struct _PRINTER_ELEMENTS_TO_SET_TYPE PRINTER_ELEMENTS_TO_SET_TYPE;
typedef struct _SET_PRINTER_ELEMENTS_REQUEST_TYPE SET_PRINTER_ELEMENTS_REQUEST_TYPE;
typedef struct _ELEMENT_TO_SET_RESULT_TYPE ELEMENT_TO_SET_RESULT_TYPE;
typedef struct _ELEMENT_TO_SET_RESULT_TYPE_LIST ELEMENT_TO_SET_RESULT_TYPE_LIST;
typedef struct _PRINTER_ELEMENTS_TO_SET_RESULTS_TYPE PRINTER_ELEMENTS_TO_SET_RESULTS_TYPE;
typedef struct _SET_PRINTER_ELEMENTS_RESPONSE_TYPE SET_PRINTER_ELEMENTS_RESPONSE_TYPE;

// 
// Structure definition ELEMENT_TO_SET_TYPE
// 
struct _ELEMENT_TO_SET_TYPE
{
    const WCHAR* ElementPath;
    WSDXML_ELEMENT* Any;
};

// 
// Structure definition ELEMENT_TO_SET_TYPE_LIST
// 
struct _ELEMENT_TO_SET_TYPE_LIST
{
    struct _ELEMENT_TO_SET_TYPE_LIST* Next;
    ELEMENT_TO_SET_TYPE* Element;
};

// 
// Structure definition PRINTER_ELEMENTS_TO_SET_TYPE
// 
struct _PRINTER_ELEMENTS_TO_SET_TYPE
{
    ELEMENT_TO_SET_TYPE_LIST* ElementToSet;
};

// 
// Structure definition SET_PRINTER_ELEMENTS_REQUEST_TYPE
// 
struct _SET_PRINTER_ELEMENTS_REQUEST_TYPE
{
    PRINTER_ELEMENTS_TO_SET_TYPE* ElementsToSet;
};

// 
// Structure definition ELEMENT_TO_SET_RESULT_TYPE
// 
struct _ELEMENT_TO_SET_RESULT_TYPE
{
    const WCHAR* ElementPath;
    const WCHAR* Result;
};

// 
// Structure definition ELEMENT_TO_SET_RESULT_TYPE_LIST
// 
struct _ELEMENT_TO_SET_RESULT_TYPE_LIST
{
    struct _ELEMENT_TO_SET_RESULT_TYPE_LIST* Next;
    ELEMENT_TO_SET_RESULT_TYPE* Element;
};

// 
// Structure definition PRINTER_ELEMENTS_TO_SET_RESULTS_TYPE
// 
struct _PRINTER_ELEMENTS_TO_SET_RESULTS_TYPE
{
    ELEMENT_TO_SET_RESULT_TYPE_LIST* ElementToSetResult;
};

// 
// Structure definition SET_PRINTER_ELEMENTS_RESPONSE_TYPE
// 
struct _SET_PRINTER_ELEMENTS_RESPONSE_TYPE
{
    PRINTER_ELEMENTS_TO_SET_RESULTS_TYPE* ElementsToSetResults;
};

// 
// ElementSetResultValuesType Values
// 
#define ElementSetResultValuesType_Succeeded            L"Succeeded"
#define ElementSetResultValuesType_ElementReadOnly      L"ElementReadOnly"
#define ElementSetResultValuesType_IncompatibleType     L"IncompatibleType"
#define ElementSetResultValuesType_InvalidElementPath   L"InvalidElementPath"
#define ElementSetResultValuesType_UnknownElementPath   L"UnknownElementPath"
#define ElementSetResultValuesType_UnknownFailure       L"UnknownFailure"

#define TYPE_ENCODING_ELEMENT_TO_SET_TYPE WSDXML_TYPE_ENCODING(0,1)
extern WSDXML_TYPE Type_ELEMENT_TO_SET_TYPE;

#define TYPE_ENCODING_PRINTER_ELEMENTS_TO_SET_TYPE WSDXML_TYPE_ENCODING(1,1)
extern WSDXML_TYPE Type_PRINTER_ELEMENTS_TO_SET_TYPE;

#define TYPE_ENCODING_SET_PRINTER_ELEMENTS_REQUEST_TYPE WSDXML_TYPE_ENCODING(2,1)
extern WSDXML_TYPE Type_SET_PRINTER_ELEMENTS_REQUEST_TYPE;

#define TYPE_ENCODING_ELEMENT_TO_SET_RESULT_TYPE WSDXML_TYPE_ENCODING(3,1)
extern WSDXML_TYPE Type_ELEMENT_TO_SET_RESULT_TYPE;

#define TYPE_ENCODING_PRINTER_ELEMENTS_TO_SET_RESULTS_TYPE WSDXML_TYPE_ENCODING(4,1)
extern WSDXML_TYPE Type_PRINTER_ELEMENTS_TO_SET_RESULTS_TYPE;

#define TYPE_ENCODING_SET_PRINTER_ELEMENTS_RESPONSE_TYPE WSDXML_TYPE_ENCODING(5,1)
extern WSDXML_TYPE Type_SET_PRINTER_ELEMENTS_RESPONSE_TYPE;


extern WSDXML_TYPE* PrinterServiceV12TypeTypes[6];

// PrinterServiceV12TypeRegisterTypes is used to register field types
// with an XML context so it can look up matching type tables.
#define PrinterServiceV12TypeRegisterTypes(pContext) pContext->SetTypes(PrinterServiceV12TypeTypes,(sizeof(PrinterServiceV12TypeTypes) / sizeof(PrinterServiceV12TypeTypes[0])),1)

//
// Port type http://schemas.microsoft.com/windows/2012/10/wdp/printV12/PrinterServiceV12Type
// Message structure definitions
//
typedef struct
{
    SET_PRINTER_ELEMENTS_REQUEST_TYPE* body;
}
REQUESTBODY_PrinterServiceV12Type_SetPrinterElements;

typedef struct
{
    SET_PRINTER_ELEMENTS_RESPONSE_TYPE* body;
}
RESPONSEBODY_PrinterServiceV12Type_SetPrinterElements;

// 
// Port type http://schemas.microsoft.com/windows/2012/10/wdp/printV12/PrinterServiceV12Type
// 
extern WSD_OPERATION Operations_PrinterServiceV12Type[1];
extern WSD_PORT_TYPE PortType_PrinterServiceV12Type;

extern WSD_HOST_METADATA hostMetadata;
extern WSD_THIS_MODEL_METADATA thisModelMetadata;
HRESULT CreatePrinterServiceV12TypeHost(
                LPCWSTR pszDeviceAddress,
                const WSD_THIS_DEVICE_METADATA* pThisDeviceMetadata,
                IPrinterServiceV12Type* pIPrinterServiceV12Type,
                IWSDDeviceHost** pHostOut,
                IWSDXMLContext** ppContextOut);
HRESULT __stdcall
Stub_SetPrinterElements
(   IUnknown* server
,   IWSDServiceMessaging* service
,   WSD_EVENT* event
);

