///////////////////////////////////////////////////////////////////////////////
//
// THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT MODIFY IT BY HAND.
//
///////////////////////////////////////////////////////////////////////////////
#pragma once

class CPrinterServiceV12TypeProxy;

HRESULT CreateCPrinterServiceV12TypeProxy(
                LPCWSTR pszDeviceAddress,
                LPCWSTR pszLocalAddress,
                CPrinterServiceV12TypeProxy** ppProxyOut,
                IWSDXMLContext** ppContextOut);

HRESULT CreateCPrinterServiceV12TypeProxyById(
                LPCWSTR pszDeviceAddress,
                LPCWSTR pszServiceId,
                LPCWSTR pszLocalAddress,
                CPrinterServiceV12TypeProxy** ppProxyOut,
                IWSDXMLContext** ppContextOut);

class CPrinterServiceV12TypeProxy: public IPrinterServiceV12TypeProxy
{
protected:
    ~CPrinterServiceV12TypeProxy();
    LONG m_cRef;
    IWSDServiceProxy* m_genericProxy;

public:
    HRESULT STDMETHODCALLTYPE Init(IWSDServiceProxy* genericProxy);
    CPrinterServiceV12TypeProxy();

    // 
    // IUnknown
    // 
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void **ppvObject);
    ULONG STDMETHODCALLTYPE AddRef();
    ULONG STDMETHODCALLTYPE Release();
    HRESULT STDMETHODCALLTYPE
    SetPrinterElements
    (   /* [in] */ SET_PRINTER_ELEMENTS_REQUEST_TYPE* body
    ,   /* [out] */ SET_PRINTER_ELEMENTS_RESPONSE_TYPE** bodyOut
    );

    HRESULT STDMETHODCALLTYPE
    BeginSetPrinterElements
    (   /* [in] */ SET_PRINTER_ELEMENTS_REQUEST_TYPE* body
    ,   /* [in] */ IUnknown* AsyncState
    ,   /* [in] */ IWSDAsyncCallback* AsyncCallback
    ,   /* [out] */ IWSDAsyncResult** AsyncResultOut
    );

    HRESULT STDMETHODCALLTYPE
    EndSetPrinterElements
    (   /* [in] */ IWSDAsyncResult* AsyncResult
    ,   /* [out] */ SET_PRINTER_ELEMENTS_RESPONSE_TYPE** bodyOut
    );


};

