<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:wsdp="http://schemas.xmlsoap.org/ws/2006/02/devprof"
             xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
             xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
             xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
             xmlns:wprt="http://schemas.microsoft.com/windows/2006/08/wdp/print"
             xmlns:wprt12="http://schemas.microsoft.com/windows/2012/10/wdp/printV12"
             targetNamespace="http://schemas.microsoft.com/windows/2012/10/wdp/printV12"
             name="WSDPrinterServiceV12">

    <xs:annotation>
        <xs:documentation>
            WSD Printer Service V1.2 Extensions Web Service Description (WSDL) file
            Copyright (c) Microsoft Corporation. All rights reserved
        </xs:documentation>
    </xs:annotation>

    <wsp:Policy wsu:Id="ServicePolicy">
        <wsdp:Profile />
    </wsp:Policy>

    <types>
        <xs:schema targetNamespace="http://schemas.microsoft.com/windows/2012/10/wdp/printV12">
            <xs:include schemaLocation="WDPPrintV12.xsd"/>
        </xs:schema>
    </types>
    <message name="SetPrinterElementsRequestMsg">
        <part name="body" element="wprt12:SetPrinterElementsRequest"/>
    </message>
    <message name="SetPrinterElementsResponseMsg">
        <part name="body" element="wprt12:SetPrinterElementsResponse"/>
    </message>

    <portType name="PrinterServiceV12Type">
        <operation name="SetPrinterElements">
            <input message="wprt12:SetPrinterElementsRequestMsg"
                   wsa:Action="http://schemas.microsoft.com/windows/2012/10/wdp/printV12/SetPrinterElements" />
            <output message="wprt12:SetPrinterElementsResponseMsg"
                   wsa:Action="http://schemas.microsoft.com/windows/2012/10/wdp/printV12/SetPrinterElementsResponse" />
        </operation>
    </portType>
    <binding name="PrinterServiceV12Binding" type="wprt:PrinterServiceV12Type">
        <wsoap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#ServicePolicy" />
        <operation name="SetPrinterElements">
            <wsoap12:operation
                soapAction="http://schemas.microsoft.com/windows/2012/10/wdp/printV12/SetPrinterElements"
                soapActionRequired="true" />
            <input>
                <wsoap12:body use="literal" />
            </input>
            <output>
                <wsoap12:body use="literal" />
            </output>
        </operation>
    </binding>
    <service name="PrinterServiceV12">
        <port name="PrinterPortV12" binding="wprt:PrinterServiceV12Binding">
            <wsoap12:address location="http://localhost/PrinterServiceV12/"/>
        </port>
    </service>
</definitions>
